spring.application.name=trade-vault

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/trading_db}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

jwt.secret=${JWT_SECRET:MySuperSecretKeyThatIsExtremelyLongAndSecure123456789!}
cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}
